namespace DrPipe.Diagnosis.Models
{
    public class DataGridModel
    {
        public DataGridModel[] Details { get; set; }
        public object Col01 { get; set; }
        public object Col02 { get; set; }
        public object Col03 { get; set; }
        public double Col04 { get; set; }
        public object Col05 { get; set; }
        public object Col06 { get; set; }
        public object Col07 { get; set; }
        public object Col08 { get; set; }
        public object Col09 { get; set; }
        public object Col10 { get; set; }
        public object Col11 { get; set; }
        public object Col12 { get; set; }
        public object Col13 { get; set; }
        public object Col14 { get; set; }
        public object Col15 { get; set; }
        public object Col16 { get; set; }
        public object Col17 { get; set; }
        public object Col18 { get; set; }
        public object Col19 { get; set; }
        public object Col20 { get; set; }
        public object Col21 { get; set; }
        public object Col22 { get; set; }
        public object Col23 { get; set; }
        public object Col24 { get; set; }
        public object Col25 { get; set; }
        public object Col26 { get; set; }
        public object Col27 { get; set; }
        public object Col28 { get; set; }
        public object Col29 { get; set; }
        public object Col30 { get; set; }
        public object Col31 { get; set; }
        public object Col32 { get; set; }
        public object Col33 { get; set; }
        public object Col34 { get; set; }
        public object Col35 { get; set; }
        public object Col36 { get; set; }
        public object Col37 { get; set; }
        public object Col38 { get; set; }
        public object Col39 { get; set; }
        public object Col40 { get; set; }
        public object Col41 { get; set; }
        public object Col42 { get; set; }
        public object Col43 { get; set; }
        public object Col44 { get; set; }
        public object Col45 { get; set; }
        public object Col46 { get; set; }
        public object Col47 { get; set; }
        public object Col48 { get; set; }
        public object Col49 { get; set; }
        public object Col50 { get; set; }
        public object Col51 { get; set; }
        public object Col52 { get; set; }
        public object Col53 { get; set; }
        public object Col54 { get; set; }
        public object Col55 { get; set; }
        public object Col56 { get; set; }
        public object Col57 { get; set; }
        public object Col58 { get; set; }
        public object Col59 { get; set; }
        public object Col60 { get; set; }
        public object Col61 { get; set; }
        public object Col62 { get; set; }
        public object Col63 { get; set; }
        public object Col64 { get; set; }
        public object Col65 { get; set; }
        public object Col66 { get; set; }
        public object Col67 { get; set; }
        public object Col68 { get; set; }
        public object Col69 { get; set; }
        public object Col70 { get; set; }
        public object Col71 { get; set; }
        public object Col72 { get; set; }
        public object Col73 { get; set; }
        public object Col74 { get; set; }
        public object Col75 { get; set; }
        public object Col76 { get; set; }
        public object Col77 { get; set; }
        public object Col78 { get; set; }
        public object Col79 { get; set; }
        public object Col80 { get; set; }
        public object Col81 { get; set; }
        public object Col82 { get; set; }
        public object Col83 { get; set; }
        public object Col84 { get; set; }
        public object Col85 { get; set; }
        public object Col86 { get; set; }
        public object Col87 { get; set; }
        public object Col88 { get; set; }
        public object Col89 { get; set; }
        public object Col90 { get; set; }
        public object Col91 { get; set; }
        public object Col92 { get; set; }
        public object Col93 { get; set; }
        public object Col94 { get; set; }
        public object Col95 { get; set; }
        public object Col96 { get; set; }
        public object Col97 { get; set; }
        public object Col98 { get; set; }
        public object Col99 { get; set; }
    }
}
